
title: "Mehul Bapat"
description: "Ph.D. candidate in Computational Fluid Mechanics"
url: "https://mhlbapat.github.io"
baseurl: ""

theme: jekyll-theme-cayman
markdown: kramdown

# Personal info
name: "Mehul Bapat"
email: "mhlbapat@gmail.com"
phone: "+1 412 886 3730"
website: "https://mhlbapat.github.io"
linkedin: "https://www.linkedin.com/in/mhlbapat"
github: "https://github.com/mhlbapat"
scholar: "https://scholar.google.com/citations?user=9zqqN1cAAAAJ"
location: "Pittsburgh, PA"

# Social links
social:
  email: "mailto:mhlbapat@gmail.com"
  github: "https://github.com/mhlbapat"
  linkedin: "https://www.linkedin.com/in/mhlbapat"
